version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo
    networks: [ webnet ]
    ports: [ "3306:3306" ]

  web:
    build: .
    depends_on: [ db ]
    networks: [ webnet ]
    ports: [ "8080:80" ]

networks:
  webnet: